FROM blcksync/alpine-node:latest

RUN apk add --no-cache make gcc g++ python git bash
COPY package.json /src/package.json
COPY package-lock.json /src/package-lock.json
WORKDIR /src
RUN npm install -S webpack@4.28.2 \
    webpack-cli@3.1.2 \
    webpack-dev-server@3.1.14 

ADD . .
RUN npm run build

EXPOSE 7545

# -h 0.0.0.0 added after ganachi 6.0.0 to listen on all interface
ENTRYPOINT ["node", "./build/cli.node.js", "-h 0.0.0.0", "-p 7545"]
